name: Stop AlgoTrader-v2

on:
  schedule:
    - cron: '35 13 * * 1-5'  # Runs every weekday at 13:35 UTC (9:35 AM EST)

jobs:
  stop:
    runs-on: ubuntu-latest

    steps:
      - name: Stop Docker container
        run: |
          docker stop algotrader-v2-container || true  # Stop container if running
          docker rm algotrader-v2-container || true    # Remove container if exists

      - name: Clean up decrypted files
        run: |
          # Remove decrypted files if needed
          rm -f strategy.py
          rm -f file_a.txt
          rm -f file_b.txt
