name: Stop AlgoTrader-v2

on:
  schedule:
    - cron: '33 13 * * 1-5'  # Runs every weekday at 13:33 UTC (9:33 AM EST)

jobs:
  stop:
    runs-on: ubuntu-latest

    steps:
      - name: Stop Docker container
        run: |
          docker stop algotrader-v2 || true  # Stop container if running
          docker rm algotrader-v2 || true    # Remove container if exists

      - name: Clean up decrypted files
        run: |
          # Remove decrypted files if needed
          rm -f strategy.py
          rm -f file.txt
          rm -f decryption_password.txt
